version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-pleasanter-dev
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Tokyo
      - TZ=Asia/Tokyo
    volumes:
      - ./volume:/home/node/.n8n
      - ./n8n-nodes-pleasanter/dist:/home/node/.n8n/custom/node_modules/n8n-nodes-pleasanter/dist:ro
      - ./n8n-nodes-pleasanter/package.json:/home/node/.n8n/custom/node_modules/n8n-nodes-pleasanter/package.json:ro
